### PR TITLE
Add Facebook integration

### PR DESCRIPTION
**Pull request by 0xTim**
This PR adds the necessary code to allow facebook login to work.

**Note:** this is currently untested as Facebook require HTTPS and I haven't had time to deploy/set up HTTPS locally. This should be done before merging. Also the Wiki needs updating.

Could be a good starter task, recommend that it doesn't get merged in until the above is resolved.

### CODE REVIEW

**Comment by calebkleveter** [comment]
Note to anyone interested in testing this, here is how to setup HTTPS behind Nginx.

1. Install Nginx

	**Homebrew:**
	
	```bash
	brew install nginx
	brew services start nginx
	```
	
	**APT:**
	
	```bash
	sudo apt-get update
	sudo apt-get install nginx
	sudo ufw allow 'Nginx HTTP'
	```
	
2. Install OpenSSL

	**Homebrew:**
	
	```bash
	brew install openssl
	```
	
	**APT:**
	
	```bash
	sudo apt-get install openssl
	sudo apt-get install libssl-dev
	```
	
3. Create `nginx.conf` File

	You will need to create a custom Nginx config in the project's root. It will look something like this:

        ```nginx
        events {}

        http {
            include /usr/local/etc/nginx/mime.types;

            server {
                listen                     3000 ssl;
                server_name         imperial.test;

                ssl_certificate        imperial.crt;
                ssl_certificate_key imperial.key;

                root /Path/to/project;

                location / {
                    proxy_pass      http://localhost:8080;
                }
            }
        }
        ```

	
4. Create an TLS Certificate

	```bash
	openssl req \
	-newkey rsa:2048 \
	-nodes \
	-keyout imperial.key \
	-x509 \
	-reqexts SAN \
	-extensions SAN \
	-config <(cat /etc/ssl/openssl.cnf \
	<(printf '[SAN]\nsubjectAltName=DNS:stripe-generator.caleb,IP:127.0.0.1')) \
	-days 365
	-out imperial.crt
	```
	
	You will need to trust the new certificate on your machine for your browser to accept it. on macOS, you can do this by opening Keychain Access and going to `File > Import items...` (or <kbd>⇧</kbd>+<kbd>⌘</kbd>+<kbd>i</kbd>). Select the `stripe.crt` file that you just created. Right click on the imported certificate and select `Get Info`. In the popup that opens, toggle the `Trust` section and set `When using this certificate` to `Always trust`. When you close the info popup, you will need to enter an admin password for the changes to persist.
	
5. Start Nginx Server

	```bash
	nginx -c $(pwd)/nginx.conf
	```

The configuration might need some tweaking, but it's a starting point.

**Comment by mariokovacevic** [comment]
Hi guys, 

I planned to add facebook also but I never had time to finish. I am also new to Vapor so this was my test project. 

I created a demo server and client app using google and facebook. Maybe you guys can check it out and see if there is something usefully to copy or use as an example for Imperial.

https://github.com/mariokovacevic/Imperial
https://github.com/mariokovacevic/VaporAuth

Keep up the good work.
Best

**Comment by natebird** [comment]
I rebased Master and now it's showing all the commits in between.

**Comment by natebird** [comment]
This should be good to merge in. I'm using it in a side application and it is working well. I also added a section for pulling user information from Facebook's Graph API to the documentation.

**Pull request merged**
