### PR TITLE
Removed due fix https://github.com/vapor/vapor/issues/2147

### PR DESCRIPTION
**Pull request by Maxim-Inv**

### CODE REVIEW

**Comment by 0xTim** [comment]
@Maxim-Inv can you bump the minimum version in the Package.swift to the version that included the fix to avoid any build errors?

**Comment by Maxim-Inv** [comment]
@0xTim done

**Comment by 0xTim** [comment]
Hmm this is going to take more work unfortunately (and nothing to do on your part). `OpenCrypto` is about to be archived in favour or `Crypto` but `Crypto` doesn't yet support PEMs so we either need to work around it or implement some extra stuff

**Comment by 0xTim** [comment]
(Primarily to remind myself - if PEM support is definitely required we might be able to borrow https://github.com/IBM-Swift/BlueECC/blob/2c4ea97307b28c1338689b4f7a4391a14c0610a4/Sources/CryptorECC/ECPrivateKey.swift which does the required ASN1 parsing to convert a PEM/DER into bytes we can use)

**Comment by 0xTim** [comment]
Has this been supersceded by #58 and 1.0.0-Beta.1?

**Comment by Maxim-Inv** [comment]
Yes, it has been superseded

**Comment by 0xTim** [comment]
OK - I'll close this then

**Pull request closed without merging**
